### ISSUE TITLE
Some error occurred when run

### ISSUE THREAD

**Issue by wayne1203** [googlemaps/roads-api-samples#1]
Hello, thanks for the application it's I needed. But I have an error when I run the application.

I think it's about the library. I found that have an error on 
"import android.util.LongSparseArray;" , "Cannot resolve symbol R" and the xml file (gpx_data.xml""http://www.topografix.com/GPX/1/1"

I just using the import function in Android Studio and the error appear.

Thanks.

**Comment by markmcd** [comment]
I can't seem to replicate the issue you're having with the latest Android Studio and SDK. Can you try upgrading to the latest versions (if you're not already) and trying again?

Otherwise try searching for ["Cannot resolve symbol R"](https://www.google.com/?q=cannot%20resolve%20symbol%20r), there are a number of resources that may be able to help you.
